### ISSUE TITLE
Dermine Train Location (Subset 026-3.6): Task List

### ISSUE THREAD

**Issue by UweSteinkeFromSiemens** [openETCS/SRS-Analysis#8]
@janWelte , @VNuhaan , @BerndHekele, @JanWelvaarts : 

The tasks for analyzing the function "Determine Train Location": 
#### Preparation:
- [ ] Algorithm description in form of mathematical equations (Jan Welvaarts + Vincent)  (11 SP)
- [ ] Interface of functions: providing trainPosition and Location types: object for train position and for location for infrastructure element. (Jan Welvaarts)  (1 SP)
- [ ] Modeling the structures in Papyrus (Bernd/Peyman)  (5 SP)
- [ ] Check the special cases with linking information document from Jan Welvaarts (Uwe)  done
- [ ] Manage profile data (MA) (Uwe)  (delay until needed)
#### Detailed functional architecture and design description (Papyrus + Scade Suite)
- [ ] Functional decomposition of "Determine Train Location"  
- [ ] Interfaces of "Determining Train Location" (inputs + outputs)
- [ ] Subfunction "Validate Input Data" (select relevant linking + balise data) (Giovanni + Bernd) 
    More complicated filtering in second step (Help with analysis Vincent)
- [ ] Subfunction "Manage LRBG" 
- [ ] Subfunction "Calculate Train Position"
- [ ] 3.6.5 "Position Reporting to the RBC" ( Peyman )
- [ ] 3.6.6 "Geographical position reporting"
#### Modelling:
- [ ] SysML Model: Define data types, flow specifications
- [ ] SysML Model: BDD, IBD functional structure
- [ ] Scade Model: Interfaces and functional structure
- [ ] Scade Model: "Validate Input Data"
- [ ] Scade Model: "Manage LRBG"
- [ ] Scade Model: "Calculate Train Position"
- [ ] Linking with Requirements
